;Copyright CANON INC. 2022
; ScanDelDrv.ini
;
; LastModified: 23-Mar-2022
;
[Setup]
DeviceName=Canon iR2224
ScanGearType=2
Resources=Resource\ScanDelDrvRes.dll
GUID={03279214-C17E-479B-AC51-44DFCE257702}
ExecMode=0
CommandLine=/S /W %x /DN "%s" /MN "%s" /CMFPUNINST /FDD /UL 1 /CALL %d /HWID "%s"

[PushScanEvent]
ExePath=Ext\SetEvent.exe
CmdLine="-e=unregist -d="%s""

[Common]
DriverGUID={2AFE101B-FEFE-4BE9-BDA3-D9C20DDD5557}
CompatibleID_USB=USB\MS_COMP_SCAN&MS_SUBCOMP_CAOPIS2
HardwareID_MFNP=CANON_MFNP
ModelNameGeneric=MFSCN
SateraVer=SateraMFP1
FolderName=CanonMF
Uninst_Reg=SOFTWARE\Canon\SGGenMFUninst\
Uninst_Key=SGGenMFUninst
DefaultDeviceDir=\MFSCN_mf52
SGVer=11.3
WIAVer=3.1

[Canon iR2224]
Model=iR2224
Driver0=SCAN,Canon iR2224,iR2224,USB\VID_04A9&PID_289B

[DriverUninstallerNames]
SCAN=HKLM,SOFTWARE\Canon\SGGenMFUninst,exePath

[DriverUninstallerNamesEx]
SCAN=DIRECT,..\%DIR_INTDRV%\SCAN%DIR_OS%%DIR_UNINSTALLER%\ScanDelDrv.exe
