;Copyright CANON INC. 2022
; Network Driver Setup
; Definition file
; LastModified: 29-Jun-2023

[Setup]
; Title, BgTitle, FontName, License can be specified in following format.
;  Title.<LangID>
; In this format, you can specify language dependent strings.
; If the .<LangID> entry not found, installer uses no extension entry.
;

;Resource 
Resources=Resource\NiHRes.dll

; devconfig_config_device timeout(IP address setting timeout)
DevconfigConfigTimeout=90

SetupRoot=..\..\
AdditionalPath=..\x64\
SetupCmdLine=/S /W %x /PRTINFO "%s,%s,%s,,%s,%s" /MN "%s" /PORT "%d,%s,%s" /CMFPINST /LANG "%s"
ScanSetupCmdLine=/S /W %x /MN "%s" /DEVINFO "%s,%s,%x" /LANG "%s" /CMFPINST

[Functions]
; Default function flags
; 0x1 Printer
; 0x2 FAX
; 0x4 Scanner
;DefaultTarget=0x7
DefaultTestPrint=0x1

[Printers]
; PrinterNames=0x1,0x2,0x4...  with ACC. Key
DefaultTestPrint=0x5

;Canon Driver Information Assist Service Install Information
[DIAS]
Version=3.40
BuildNumber=3407
ServiceStart=1
;Path from Setup.exe 
SetupPath=misc\DIAS\DiasSetup.msi
DiskSpace=20

[PortMonitor]
SetupPath=.\misc\Ext\PMon\MFPMIN.dll
UninstPath=.\misc\Ext\PMon\MFPMUI.ex_

[PortCommunication]
SetupPath=.\misc\Ext\PCom\MFPCIN.dll
UninstPath=.\misc\Ext\PCom\MFPCUI.ex_

[ScannerSelector]
SetupPath=.\misc\Ext\SS\MFNSSIN.ex_
CommandLine="-NOEULA -NOCONFIRMMSG -MODELNAME "%s""

[DiscoverData]
Methods=4
Character=65001
Timeout=600
Retry=3

[PortSetting]
Allow_Port=0
Allow_IP=0

[Supported Devices]
; canPdInfoProductName = <Section Name>
iR2224=Canon iR2224

[Canon iR2224]
Model=iR2224
; Implemented function flags
; 0x1 Printer
; 0x2 FAX
; 0x4 Scanner
Functions=0x7
DiskSpace=20
PrinterNames=10023, ,10028
;add these numbers BDL=1,PCL5=2,PCL6=4,PS=8,V4=16
ExistingDriverBit=0x5
; Implemented Support Printer flags
; Refer to [Printers] Section
Printers=0x5
;DefaultPrinters=0x5
V4Driver=0x0
PortType=2

[Canon iR2224.PRINT.1]
DriverName=Canon Generic Plus UFR II V290
DispDriverName=Generic Plus UFR II Printer Driver
DefaultDeviceName=Canon iR2224 UFR II
PortType=2
AdditionalDriver=1
DiskSpace.x86=250
DiskSpace.x64=270

[Canon iR2224.PRINT.4]
DriverName=Canon Generic Plus PCL6 V290
DispDriverName=Generic Plus PCL6 Printer Driver
DefaultDeviceName=Canon iR2224 PCL6
PortType=2
AdditionalDriver=1
DiskSpace.x86=80
DiskSpace.x64=110

[Canon iR2224.FAX]
DriverName=Canon Generic FAX Driver (FAX)
DispDriverName=Generic FAX Driver
DefaultDeviceName=Canon iR2224 FAX
PortType=2
AdditionalDriver=1
DiskSpace.x86=100
DiskSpace.x64=110

[Canon iR2224.SCAN]
DispDriverName=Canon iR2224
DriverName=iR2224
DiskSpace.x86=200
DiskSpace.x64=200

[RegistrationAPI]
SilentOption=0
