;Copyright CANON INC. 2022
; DelDrv.ini
;
; LastModified: 29-Jun-2023
;
[Setup]
GUID={F2755F82-E05B-422C-A4AA-88A758AF3CEC}
Version=7.70
DeviceName=Canon iR2224
CommandLine=/S /W %x /DN "%s" /MN "%s" /CMFPUNINST /FDD /UL 1 /CALL %d /HWID "%s"
ScanGearType=2

;String ini
Strings=SetupRes.ini
;Resource 
Resources=%FILE_DELDRV_RESOURCES%

[Canon iR2224]
Model=iR2224
Driver0=BDL,Canon Generic Plus UFR II V290,Canon iR2224 UFR II,CanoniR2224_UFR_II1185
Driver1=PCL6,Canon Generic Plus PCL6 V290,Canon iR2224 PCL6,CanoniR2224_PCL6D725
Driver2=FAX,Canon Generic FAX Driver (FAX),Canon iR2224 FAX,CanoniR2224_FAX8FE2
Driver3=SCAN,Canon iR2224,iR2224,USB\VID_04A9&PID_289B

[DriverUninstallerNames]
BDL=HKLM,SOFTWARE\Canon\PrnUninst,exePath
PCL6=HKLM,SOFTWARE\Canon\PrnUninst,exePath
FAX=HKLM,SOFTWARE\Canon\PrnUninst,exePath
SCAN=HKLM,SOFTWARE\Canon\SGGenMFUninst,exePath

[DriverUninstallerNamesEx]
BDL=DIRECT,..\%DIR_INTDRV%\UFRII%DIR_OS%%DIR_UNINSTALLER%%PATH_UNINSATLLER%
PCL6=DIRECT,..\%DIR_INTDRV%\PCL6%DIR_OS%%DIR_UNINSTALLER%%PATH_UNINSATLLER%
FAX=DIRECT,..\%DIR_INTDRV%\FAX%DIR_OS%%DIR_UNINSTALLER%%PATH_UNINSATLLER%
SCAN=DIRECT,..\%DIR_INTDRV%\SCAN%DIR_OS%%DIR_UNINSTALLER%\ScanDelDrv.exe

[PushScanEvent]
ExePath=\Ext\SetEvent.exe
CmdLine="-e=unregist -d="%s""

;-------------------------------------------------------------
; OPTIONAL
;-------------------------------------------------------------
[OS]
Srv2008_Edition=00003DC010003800
