;Copyright CANON INC. 2022
; StringTable
;
; LastModified: 23-Mar-2022
;
[Strings]
FILE_LICENSE_REGION=misc\EULA\License.rtf
FILE_RESOURCES=misc\Resource\IstDrvRes.dll
FILE_DELDRV_RESOURCES=Resource\DelDrvRes.dll
DIR_OS=\x64
DIR_LANG=
DIR_INTDRV=..\..\intdrv
DIR_UNINSTALLER=\misc
PATH_INSTALLER=\Setup.exe
PATH_UNINSATLLER=\UNINSTAL.exe
PATH_README=\Readme.hta
