;Copyright CANON INC. 2022
; ScanSetup.ini
;
; LastModified: 23-Mar-2022
;
[Setup]
;-------------------------------------------------------------
; MUST
;-------------------------------------------------------------
; Default Target Directory
DefaultTargetDir=\CanonMF
DriverDir=\Driver
ExecMode=0
;-------------------------------------------------------------
; OPTIONAL
;-------------------------------------------------------------
; Readme File
Readme=Readme\Readme_SG.hta

; License Agreement
License=%FILE_LICENSE_REGION%

;String ini
Strings=misc\ScanSetupRes.ini

;Resource 
Resources=%FILE_RESOURCES%

;Uninstaller
[Uninstaller]
Version=2.5.0.0
UninstallerGUID={03279214-C17E-479B-AC51-44DFCE257702}
Files.WINNT5=misc\ScanDelDrv.exe,misc\ScanDelDrv.ini,misc\Resource\ScanDelDrvRes*.DLL,misc\ScanSetupRes.ini,misc\Ext\SETEVENT.exe,misc\Ext\PCom\MFPCUI.ex_,misc\Ext\PCom\MFPCIU.ini,misc\Ext\PMon\MFPMUI.ex_,misc\Ext\PMon\MFPMIU.ini,misc\Ext\SS\MFNSSUI.ex_,misc\Ext\SS\MFNSSIU.ini
Files.WINNT5_x64=misc\ScanDelDrv.exe,misc\ScanDelDrv.ini,misc\Resource\ScanDelDrvRes*.DLL,misc\ScanSetupRes.ini,misc\Ext\SETEVENT.exe,misc\Ext\PCom\MFPCUI.ex_,misc\Ext\PCom\MFPCIU.ini,misc\Ext\PMon\MFPMUI.ex_,misc\Ext\PMon\MFPMIU.ini,misc\Ext\SS\MFNSSUI.ex_,misc\Ext\SS\MFNSSIU.ini
Files.WINXP_x64=misc\ScanDelDrv.exe,misc\ScanDelDrv.ini,misc\Resource\ScanDelDrvRes*.DLL,misc\ScanSetupRes.ini,misc\Ext\SETEVENT.exe,misc\Ext\PCom\MFPCUI.ex_,misc\Ext\PCom\MFPCIU.ini,misc\Ext\PMon\MFPMUI.ex_,misc\Ext\PMon\MFPMIU.ini,misc\Ext\SS\MFNSSUI.ex_,misc\Ext\SS\MFNSSIU.ini
TargetDir=CanonSGMF Uninstaller Information
CommandLine=/U:%s /V "%s" /L "%s"

[ServicePacks]
WIN2K=0
WINXP=0
WINXP_x64=0

[NetworkWIAInstaller]
SetupPath=.\misc\Ext\nwiainst.ex_

[NetworkWIAInstance]
SetupPath=.\misc\Ext\nwiastup.ex_

[PushScanEvent]
ExePath=\misc\Ext\SetEvent.exe
CmdLine="-e=regist -d="%s" -l="%s\Canon\MF Scan Utility\MFSCANUTILITY.exe""

[Extension]
; Can be specified .x86, .x64
; Righthand value is <ExtensionID>,<DLLNAME>,<DLLEntryPoint>
; You can run extension directory by using /X<ExtensionID> commandline option.
;
%NAME_USB%=USB|DEFAULT
%NAME_NETWORK%=NET,misc\EXT\NiHelper.dll,HELPER_LaunchNetworkInstaller

[DiscoverData]
Methods=4
Character=65001
Timeout=600
Retry=3

[PortMonitor]
SetupPath=.\misc\Ext\PMon\MFPMIN.dll
UninstPath=.\misc\Ext\PMon\MFPMUI.ex_

[PortCommunication]
SetupPath=.\misc\Ext\PCom\MFPCIN.dll
UninstPath=.\misc\Ext\PCom\MFPCUI.ex_

[ScannerSelector]
SetupPath=.\misc\Ext\SS\MFNSSIN.ex_
CommandLine="-NOEULA -NOCONFIRMMSG -MODELNAME "%s""

[Common]
Diskspace=220
DefaultDeviceDir=\MFSCN_mf52
WIAInstallerCmdLine=/I:"CANON_MFNP&%MODEL_NAME%"
MDL=%MODEL_NAME%
ModelNameGeneric=MFSCN
KEY=HKLM,Software\Wow6432Node\Canon\SateraMFP1\ScanGear\11.3\Devices\%MODEL_NAME%
CopyInfName=MFSCN.INF
CopyCabName=Scan.cab
; 0x1 TWAIN&WIA
; 0x2 WIA Only
InstScanDriver=0x1
Uninst_Reg=SOFTWARE\Canon\SGGenMFUninst\
Uninst_Path=\Canon\SGGenMFUninstall\
InfGuid={2AFE101B-FEFE-4BE9-BDA3-D9C20DDD5557}
ScannerHWID=USB\MS_COMP_SCAN&MS_SUBCOMP_CAOPIS2
DispDriverName=Canon iR2224

[DriverInstallerNames]
SCAN=%DIR_INTDRV%\SCAN%DIR_OS%\ScanSetup.exe

[pdInfoTransrateTable]
iR2224=iR2224

[HardwareID]
iR2224=USB\VID_04A9&PID_289B
